name: Go Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
