name: Go Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_coverage:
    name: Unit Tests Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test & Coverage
        run: |
          go install github.com/ory/go-acc@v0.2.6
          go-acc -o coverage.txt `go list ./... | grep -v node/tests` -- -v
      - uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.txt
  unit_race_test:
    name: Run Unit Tests with Race Detector
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: execute test run
        run: make test-unit-race
  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Swamp Tests
        run: make test-swamp
      - name: Swamp Tests with Race Detector
        run: make test-swamp-race
